name: Build Where Is This Icon?

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Android 32-bit
      - name: Build Geode mod (Android32)
        id: build-android32
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: given
          target: Android32
          build-config: Release

      - name: Upload .geode (Android32)
        uses: actions/upload-artifact@v4
        with:
          name: WhereIsThisIcon-Android32
          path: ${{ steps.build-android32.outputs.build-output }}/*.geode

      # PC / Desktop
      - name: Build Geode mod (Desktop)
        id: build-desktop
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: given
          target: Desktop
          build-config: Release

      - name: Upload .geode (Desktop)
        uses: actions/upload-artifact@v4
        with:
          name: WhereIsThisIcon-Desktop
          path: ${{ steps.build-desktop.outputs.build-output }}/*.geode
